accounts/urls.py
from django.urls import path
from .views import *
app_name = 'accounts'
urlpatterns = [
 path('register/', UserCreateView.as_view(), name='register'),
 path('register/done', UserCreateDoneView.as_view(), name='register_done'),
]

blog/urls.py
from django.urls import path, re_path
from blog.views import *
app_name = 'blog'
urlpatterns = [
 path('', PostListView.as_view(), name='index'),
 path('<int:pk>/', PostDetailView.as_view(), name='detail'),
 # Example: /blog/add/
 path('add/', PostCreateView.as_view(), name="add"),
 # Example: /blog/99/update/
 path('<int:pk>/update/', PostUpdateView.as_view(), name="update"),
 # Example: /blog/99/delete/
 path('<int:pk>/delete/', PostDeleteView.as_view(), name="delete"),
]

bookmark/urls.py
from django.urls import path
from bookmark.views import *
app_name = 'bookmark'
urlpatterns = [
 path('', BookmarkListView.as_view(), name='index'),
 path('<int:pk>/', BookmarkDetailView.as_view(), name='detail'),
 # Example: /bookmark/add/
 path('add/', BookmarkCreateView.as_view(), name="add"),
 # Example: /bookmark/change/
 path('change/', BookmarkChangeListView.as_view(), name="change"),


 # Example: /bookmark/99/update/
 path('<int:pk>/update/', BookmarkUpdateView.as_view(), name="update"),
 # Example: /bookmark/99/delete/
 path('<int:pk>/delete/', BookmarkDeleteView.as_view(), name="delete"),


]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from mysite.views import HomeView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

class Post(models.Model):
 title = models.CharField(verbose_name='TITLE', max_length=50)
 description = models.CharField('DESCRIPTION', max_length=100, 
 blank=True, help_text='simple description text.')
 content = models.TextField('CONTENT')
 create_dt = models.DateTimeField('CREATE DATE', auto_now_add=True)
 modify_dt = models.DateTimeField('MODIFY DATE', auto_now=True)
 owner = models.ForeignKey(User, on_delete=models.CASCADE, 
                                verbose_name='OWNER', blank=True, null=True)

class Meta:
    verbose_name = 'post'
    verbose_name_plural = 'posts'
    db_table = 'blog_posts' # 테이블명 재정의
    ordering = ('-modify_dt',) # orderby 절, -이면 내림차순
def __str__(self):
        return self.title
def get_absolute_url(self): # 현재 데이터의 절대 경로 추출
        return reverse('blog:detail', args=(self.id,))
def get_previous(self): # 이전 데이터 추출
        return self.get_previous_by_modify_dt()
def get_next(self): # 다음 데이터 추출
        return self.get_next_by_modify_dt()

bookmark/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Bookmark(models.Model):
 title = models.CharField('TITLE', max_length=100, blank=True)
 url = models.URLField('URL', unique=True)
 owner = models.ForeignKey(User, on_delete=models.CASCADE, blank=True,
 null=True)
 def __str__(self):
    return self.title

accounts/views.py
from django.shortcuts import render

from django.views import generic
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.contrib.auth.mixins import AccessMixin
from django.views.defaults import permission_denied

class UserCreateView(generic.CreateView): 
 template_name = 'registration/register.html' 
 form_class = UserCreationForm
 success_url = reverse_lazy('accounts:register_done') 
class UserCreateDoneView(generic.TemplateView): 
 template_name = 'registration/register_done.html'



class OwnerOnlyMixin(AccessMixin):
 raise_exception = True
 permission_denied_message = "Owner only can update/delete the object"
 def get(self, request, *args, **kwargs):
    self.object = self.get_object() # 모델 인스턴스 얻기
    if self.request.user != self.object.owner:
        self.handle_no_permission()
    return super().get(request, *args, **kwargs)

blog/views.py
from django.shortcuts import render
from django.views.generic import CreateView, UpdateView, DeleteView, ListView, DetailView
from blog.models import Post
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from accounts.views import OwnerOnlyMixin
# ListView
class PostListView(ListView):
 model = Post
 template_name = 'blog/post_all.html' # 템플릿 파일명 변경
 context_object_name = 'posts' # 컨텍스트 객체 이름 변경(object_list)
 paginate_by = 2 # 페이지네이션, 페이지당 문서 건 수
# DetailView
class PostDetailView(DetailView):
 model = Post

class PostCreateView(LoginRequiredMixin, CreateView):
 model = Post
 fields = ['title', 'description', 'content']
 success_url = reverse_lazy('blog:index')
 
 def form_valid(self, form):
    form.instance.owner = self.request.user
    return super().form_valid(form)

class PostUpdateView(OwnerOnlyMixin, UpdateView):
 model = Post
 fields = ['title', 'description', 'content']
 success_url = reverse_lazy('blog:index')

class PostDeleteView(OwnerOnlyMixin, DeleteView) :
 model = Post
 success_url = reverse_lazy('blog:index')
 
 def get(self, *args, **kwargs):
    return self.post(*args, **kwargs)

bookmark/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from bookmark.models import Bookmark
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from accounts.views import OwnerOnlyMixin

class BookmarkListView(ListView):
 model = Bookmark
class BookmarkDetailView(DetailView):
 model = Bookmark

class BookmarkCreateView(LoginRequiredMixin, CreateView):
 model = Bookmark
 fields = ['title', 'url'] # form 클래스에서 사용할 필드form 클래스 자동생성
 success_url = reverse_lazy('bookmark:index')
 
 def form_valid(self, form): # post 요청시 form의 유효성 검사 통과되면 호출
 # form.instance : 폼 정보를 기반으로 생성된 모델 인스턴스
    form.instance.owner = self.request.user # 로그인 사용자 정보
    return super().form_valid(form) # 모델 인스턴스 저장

class BookmarkChangeListView(LoginRequiredMixin, ListView): 
 template_name = 'bookmark/bookmark_change_list.html' 
 
 def get_queryset(self):
    return Bookmark.objects.filter(owner=self.request.user)

class BookmarkUpdateView(OwnerOnlyMixin, UpdateView): 
 model = Bookmark 
 fields = ['title', 'url'] # 폼 모델에 사용할 필드  폼 모델 자동 생성
 success_url = reverse_lazy('bookmark:change') 

class BookmarkDeleteView(OwnerOnlyMixin, DeleteView): 
 model = Bookmark 
 success_url = reverse_lazy('bookmark:change')
 def get(self, *args, **kwargs):
   return self.post(*args, **kwargs)

mysite/views.py
from django.views.generic import TemplateView

class HomeView(TemplateView):
    template_name = 'home.html'

blog/templates/blog/post_all.html
{% extends 'base.html' %}
{% block content-header %}
<h1><i class="fas fa-list"></i> Blog 목록</h1>
{% endblock %}

{% block content%}
{%for post in posts%}
<h3><a href="{{post.get_absolute_url}}">{{post.title}}</a></h3>
<i class="far fa-clock"></i> {{post.modify_dt|date:"Y-m-d"}}
<p>{{post.description}}</p>
{% endfor %}
<div>
    <span>
        {% if page_obj.has_previous %}
            <a href="?page={{page_obj.previous_page_number}}">Prev</a>
       
        {% endif %}
       
        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages}}
      
        {% if page_obj.has_next %}
             <a href="?page={{page_obj.next_page_number}}">Next</a>
        {% endif %}
    </span>
</div>

{% if user.is_active %}
 <div class="text-right mr-3">
 <a href="{%url 'blog:add' %}" class="btn btn-primary btn-sm">
 <i class="fas fa-pencil-alt"></i> 쓰기</a>
 </div>
 {% endif %}

{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% block content-header %}
<h1><i class="fas fa-list"></i> {{object.title}}</h1>
{% endblock %}
{% block content%}
<p>
    {%if object.get_previous %}
    <a href="{{object.get_previous.get_absolute_url}}" title="이전 글">prev</a>
    {%endif%}
    {%if object.get_next %}
    <a href="{{object.get_next.get_absolute_url}}" title="다음 글">next</a>
    {%endif%}
</p>
<p>{{object.modify_dt|date:"Y-m-d"}}</p>
{% if user == post.owner %}
<div class="text-right">
 <a href="{% url 'blog:update' post.id %}" class="mr-3">
 <i class="far fa-edit"></i> 수정</a>
 <a href="javascript:deletePost('{% url 'blog:delete' post.id %}')" 
 class="text-danger mr-3"><i class="fas fa-trash"></i> 삭제</a>
 </div>
{% endif %}

<div>    
    {% autoescape off %}
    {{object.content}}     
    {% endautoescape %}   
</div>
{% endblock %}

{% block script %}
<script>
function deleteBookmark(url) {
 if(!confirm('삭제할까요?')) {
 return
 }
 
 location= url
}
</script>
{% endblock %}

blog/templates/blog/post_form.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block content-header %}
<h1><i class="nav-icon fas fa-blog"></i> Post 생성/수정 - {{user}}</h1>
{% endblock %}
{% block content %}
<div class=my-5>
 <form action="." method="post" class="form col-sm-8 mx-auto">
 {% csrf_token %}
 {% bootstrap_form form %}
 <button type="submit" class="btn btn-primary">
 <i class="fas fa-check"></i> 확인
 </button>
 <a href="javascript:history.back()" class="btn btn-primary">
 <i class="fas fa-undo"></i> 취소
 </a> 
 </form>
</div>
{% endblock %}

{% load static %}
{% block style %}
<link rel="stylesheet" 
 href="{% static 'plugins/summernote/summernote-bs4.min.css' %}">
{% endblock %}
{% block script %}
<script src="{% static 'plugins/summernote/summernote-bs4.min.js' %}">
</script>
<script>
$(function () {
 // Summernote
 $('#id_content').summernote({
 height: 300
 })
})
</script>
{% endblock %}

bookmark/templates/bookmark/bookmark_change_list.html
{% extends "base.html" %}
{% block content-header %}
<h1><i class="fas fa-list"></i> Bookmark 수정 목록</h1>
{% endblock %}
{% block content %}
<div class="m-3">
    <table class="table table-bordered table-condensed table-striped">
        <thead>
            <tr class="table-primary">
                <th>Title</th>
                <th>Url</th>
                <th>Owner</th>
                <th>Update</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            {% for item in object_list %}
            <tr>
                <td>{{ item.title }}</td>
                <td>{{ item.url }}</td>
                <td>{{ item.owner }}</td>
                <td><a href="{% url 'bookmark:update' item.id %}">
                        <i class="far fa-edit"></i> 수정</a>
                    </a></td>
                <td><a href="javascript:deleteBookmark('{% url 'bookmark:delete' item.id %}')">
                        <i class="fas fa-trash"></i> 삭제</a>
                    </a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}
{% block script %}
<script>
function deleteBookmark(url) {
 if(!confirm('삭제할까요?')) {
 return
 }
 
 location= url
}
</script>
{% endblock %}

bookmark/templates/bookmark/bookmark_detail.html
{% extends "base.html" %}
{% block content-header %}
 <h1>Bookmark Detail</h1>
{% endblock %}
{% block content %}
<div>
 <div>
 <h3><i class="nav-icon fas fa-bookmark"></i>{{object.title}}</h3>
 <ul>
 <li>URL : <a href="{{object.url}}" target="_blank">{{object.url}}</a></li>
 </ul>
 </div>

 <div class="ml-5">
    <a href="javascript:history.back()" class="btn btn-primary btn-sm">
        <i class="fas fa-undo"></i> 돌아가기
    </a>    
 </div>
{% endblock %}

bookmark/templates/bookmark/bookmark_form.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block content-header %}
<h1><i class="nav-icon fas fa-bookmark"></i> Bookmark 생성/수정 - {{user}}</h1>
{% endblock %}
{% block content %}
<div class=my-5>
 <form action="." method="post" class="form col-sm-6 mx-auto">
 {% csrf_token %}
 {% bootstrap_form form %}
 <button type="submit" class="btn btn-primary">
 <i class="fas fa-check"></i> 확인
 </button>
 <a href="javascript:history.back()" class="btn btn-primary">
 <i class="fas fa-undo"></i> 취소</a> 
 </form>
</div>
{% endblock %}

bookmark/templates/bookmark/bookmark_list.html
{% extends "base.html" %}
{% block content-header %}<h1>Bookmark List</h1>{% endblock %}
{% block content %}
<div class="m-3">
    <ul>
        {% for bookmark in object_list %}
        <li>
            <a href="{% url 'bookmark:detail' bookmark.id %}">{{bookmark}}</a>
        </li>
        {% endfor %}
    </ul>
    {% if user.is_active %}
    <a href="{% url 'bookmark:add' %}" class="btn btn-primary btn-sm">
        <i class="fas fa-edit"></i> 추가</a>
    <a href="{%url 'bookmark:change' %}" class="btn btn-primary btn-sm">
        <i class="fas fa-pencil-alt"></i> 수정 목록</a>
    {% endif %}
</div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>IoT Dashboard</title>

    <!-- 스타일 -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/css/adminlte.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    {% block style %}{% endblock %}
</head>
<body class="hold-transition sidebar-mini">
    <div class="wrapper">
        {% include "menu.html" %}
    
        {% include "left-aside.html" %}
    
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <div class="content-header">
                <div class="container-fluid">
                {% block content-header %}{% endblock %}
                </div>
            </div>
            <div class="content">
                <div class="container-fluid">
                {% block content %}{% endblock %}
                </div>
            </div>
        </div>
        {% include "footer.html" %}
    <!-- 기본 스크립트 -->
    <script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'adminlte/js/adminlte.min.js' %}"></script>

    {% block script %}{% endblock %}
</body>

</html>
    

templates/footer.html
<!-- Main Footer -->
<footer class="main-footer">
    <!-- To the right -->
    <div class="float-right d-none d-sm-inline">
        IoT 
    </div>
    <!-- Default to the left -->
    <strong>
       Copyright &copy; 2021 <a href="http://127.0.0.1">IoT Dashboard</a>. 
    </strong> 
    All rights reserved.
</footer>

templates/home.html
{% extends 'base.html' %}
{% block content-header %}
 <h1 class="m-0">IoT Dashboard Home</h1>
{% endblock %}
{% block content %}
 <h3> 환영합니다. </h3>
{% endblock %}

templates/left-aside.html
{% load static %}
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="{% url 'home' %}" class="brand-link">
        <span class="brand-text font-weight-light">IoT Dashboard</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-item">
                    <a href="{% url 'bookmark:index' %}" class="nav-link">
                        <i class="nav-icon fas fa-bookmark"></i>
                        <p>Bookmark <span class="right badge badge-danger">
                                New</span></p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'blog:index' %}" class="nav-link">
                        <i class="nav-icon fas fa-blog"></i>
                        <p>Blog <span class="right badge badge-danger">
                                New</span></p>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</aside>

templates/menu.html
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- 좌측 메뉴 그룹 -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="{% url 'home' %}" class="nav-link">
                <i class="fas fa-home"></i> Home</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="https://adminlte.io/themes/AdminLTE/index2.html" target="_blank" class="nav-link">AdminLte</a>
        </li>

    </ul>
    <!-- 우측 메뉴 그룹 -->
    <ul class="navbar-nav ml-auto">
        {% if user.is_active %}
        <!-- 로그인 상태 -->
        <li class="nav-item d-none d-sm-inline-block">
            <a class="nav-link" href="{% url 'password_change' %}">
                <i class="fas fa-user"></i> {{user.username}}</a></li>
        <li class="nav-item d-none d-sm-inline-block">
            <a class="nav-link" href="{% url 'logout' %}">
                <i class="fas fa-sign-out-alt"></i> 로그아웃</a></li>
        {% else %}
        <!-- 로그아웃 상태 -->
        <li class="nav-item d-none d-sm-inline-block">
            <a class="nav-link" href="{% url 'login' %}">
                <i class="fas fa-sign-in-alt"></i> 로그인</a></li>
        <li class="nav-item d-none d-sm-inline-block">
            <a class="nav-link" href="{% url 'accounts:register' %}">
                <i class="fas fa-user-plus"></i> 회원가입</a></li>
        {% endif %}
    </ul>
</nav>